"""major_database_upgrade

Revision ID: b83facb167dd
Revises: 2d43fcfec50e
Create Date: 2026-06-28 14:33:35.639348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b83facb167dd'
down_revision = '2d43fcfec50e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('scheduled_date', sa.String(length=150), nullable=True),
    sa.Column('scheduled_time', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('subject', sa.String(length=30), nullable=True),
    sa.Column('audience', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcements_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_audience'), ['audience'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_subject'), ['subject'], unique=False)

    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=30), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignments_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_subject'), ['subject'], unique=False)

    op.create_table('live_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=30), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('live_class', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_class_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_class_subject'), ['subject'], unique=False)

    op.create_table('user_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_answer', sa.String(length=1), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_history_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_history_user_id'), ['user_id'], unique=False)

    op.create_table('assignment_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'position', name='uq_assignment_position'),
    sa.UniqueConstraint('assignment_id', 'question_id', name='uq_assignment_question')
    )
    with op.batch_alter_table('assignment_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignment_questions_assignment_id'), ['assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_questions_question_id'), ['question_id'], unique=False)

    op.create_table('assignment_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('submit_status', sa.Enum('pending', 'submitted', 'graded', name='submission_status'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'student_id', name='unique_assignment_submission')
    )
    with op.batch_alter_table('assignment_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignment_submissions_assignment_id'), ['assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_submissions_student_id'), ['student_id'], unique=False)

    op.create_table('live_quiz_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('live_quiz_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('selected_answer', sa.String(length=1), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['live_quiz_id'], ['live_class.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('live_quiz_id', 'question_id', 'student_id', name='uq_livequiz_question_student')
    )
    with op.batch_alter_table('live_quiz_answers', schema=None) as batch_op:
        batch_op.create_index('idx_quiz_student_score', ['live_quiz_id', 'student_id', 'score'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_quiz_answers_live_quiz_id'), ['live_quiz_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_quiz_answers_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_quiz_answers_student_id'), ['student_id'], unique=False)

    op.create_table('live_quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('live_class_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['live_class_id'], ['live_class.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('live_quiz_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_quiz_questions_live_class_id'), ['live_class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_quiz_questions_question_id'), ['question_id'], unique=False)

    op.create_table('live_quiz_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('live_class_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('correct_answers <= total_questions', name='check_correct_answers'),
    sa.CheckConstraint('correct_answers >= 0', name='check_positive_correct_answers'),
    sa.CheckConstraint('percentage >= 0 AND percentage <= 100', name='check_percentage_range'),
    sa.CheckConstraint('rank > 0', name='check_positive_rank'),
    sa.CheckConstraint('total_questions >= 0', name='check_positive_total_questions'),
    sa.CheckConstraint('total_score >= 0', name='check_positive_score'),
    sa.ForeignKeyConstraint(['live_class_id'], ['live_class.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('live_class_id', 'student_id', name='uq_live_class_student')
    )
    with op.batch_alter_table('live_quiz_results', schema=None) as batch_op:
        batch_op.create_index('ix_live_class_rank', ['live_class_id', 'rank'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_quiz_results_live_class_id'), ['live_class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_quiz_results_student_id'), ['student_id'], unique=False)

    op.create_table('student_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option', sa.String(length=1), nullable=True),
    sa.Column('text_answer', sa.Text(), nullable=True),
    sa.Column('score_awarded', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('graded_at', sa.DateTime(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("selected_option IS NULL OR selected_option IN ('A','B','C','D')", name='check_valid_answer'),
    sa.CheckConstraint('NOT (selected_option IS NOT NULL AND text_answer IS NOT NULL)', name='check_single_answer_type'),
    sa.CheckConstraint('score_awarded >= 0', name='check_positive_score'),
    sa.CheckConstraint('selected_option IS NOT NULL OR text_answer IS NOT NULL', name='check_answer_exists'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id'], ['assignment_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'question_id', name='uq_submission_question')
    )
    with op.batch_alter_table('student_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_answers_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_answers_submission_id'), ['submission_id'], unique=False)

    op.drop_table('announcement')
    op.drop_table('quiz_history')
    op.drop_table('class_status')
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('difficulty', sa.Enum('DOK_1', 'DOK_2', 'DOK_3', 'DOK_4', name='difficulty_level'), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_question_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_subject'), ['subject'], unique=False)

    with op.batch_alter_table('today_quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_today_quote_admin_id'), ['admin_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['admin_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('questions_attempted', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('correct_answers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_attempt', sa.DateTime(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_user_progress_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_progress_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('unique_user_subject', ['user_id', 'subject'])
        batch_op.drop_constraint(batch_op.f('user_progress_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('topics')
        batch_op.drop_column('total_score')
        batch_op.drop_column('quizzes_taken')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))

    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quizzes_taken', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_score', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('topics', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_progress_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_constraint('unique_user_subject', type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_progress_subject'))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('last_attempt')
        batch_op.drop_column('correct_answers')
        batch_op.drop_column('questions_attempted')
        batch_op.drop_column('subject')

    with op.batch_alter_table('today_quote', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_today_quote_admin_id'))
        batch_op.drop_column('admin_id')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_subject'))
        batch_op.drop_index(batch_op.f('ix_question_difficulty'))
        batch_op.drop_index(batch_op.f('ix_question_created_at'))
        batch_op.drop_column('created_at')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('subject')

    op.create_table('class_status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_live', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('link', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('class_status_pkey'))
    )
    op.create_table('quiz_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('quiz_history_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('quiz_history_pkey'))
    )
    op.create_table('announcement',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('Announcement_pkey'))
    )
    with op.batch_alter_table('student_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_answers_submission_id'))
        batch_op.drop_index(batch_op.f('ix_student_answers_question_id'))

    op.drop_table('student_answers')
    with op.batch_alter_table('live_quiz_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_quiz_results_student_id'))
        batch_op.drop_index(batch_op.f('ix_live_quiz_results_live_class_id'))
        batch_op.drop_index('ix_live_class_rank')

    op.drop_table('live_quiz_results')
    with op.batch_alter_table('live_quiz_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_quiz_questions_question_id'))
        batch_op.drop_index(batch_op.f('ix_live_quiz_questions_live_class_id'))

    op.drop_table('live_quiz_questions')
    with op.batch_alter_table('live_quiz_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_quiz_answers_student_id'))
        batch_op.drop_index(batch_op.f('ix_live_quiz_answers_question_id'))
        batch_op.drop_index(batch_op.f('ix_live_quiz_answers_live_quiz_id'))
        batch_op.drop_index('idx_quiz_student_score')

    op.drop_table('live_quiz_answers')
    with op.batch_alter_table('assignment_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_submissions_student_id'))
        batch_op.drop_index(batch_op.f('ix_assignment_submissions_assignment_id'))

    op.drop_table('assignment_submissions')
    with op.batch_alter_table('assignment_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_questions_question_id'))
        batch_op.drop_index(batch_op.f('ix_assignment_questions_assignment_id'))

    op.drop_table('assignment_questions')
    with op.batch_alter_table('user_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_history_question_id'))

    op.drop_table('user_history')
    with op.batch_alter_table('live_class', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_class_subject'))
        batch_op.drop_index(batch_op.f('ix_live_class_admin_id'))

    op.drop_table('live_class')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignments_subject'))
        batch_op.drop_index(batch_op.f('ix_assignments_deadline'))
        batch_op.drop_index(batch_op.f('ix_assignments_admin_id'))

    op.drop_table('assignments')
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcements_subject'))
        batch_op.drop_index(batch_op.f('ix_announcements_audience'))
        batch_op.drop_index(batch_op.f('ix_announcements_admin_id'))

    op.drop_table('announcements')
    # ### end Alembic commands ###
