"""Use database timestamps for extra class payments

Revision ID: 741c0fec32ec
Revises: 3192d6ac211
Create Date: 2026-10-04 13:01:29.782071

This migration is intentionally limited to timestamp handling for
extra_class_payments. The original autogenerated migration detected many
unrelated model/database differences and must not apply those changes.
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "741c0fec32ec"
down_revision = "3192d6ac211"
branch_labels = None
depends_on = None


def upgrade():
    # Let PostgreSQL assign creation/update timestamps using the database
    # clock instead of Python datetime values.
    op.alter_column(
        "extra_class_payments",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        existing_nullable=False,
        server_default=sa.text("CURRENT_TIMESTAMP"),
    )

    op.alter_column(
        "extra_class_payments",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        existing_nullable=False,
        server_default=sa.text("CURRENT_TIMESTAMP"),
    )

    # Keep updated_at correct even when a payment row is changed directly
    # in PostgreSQL rather than through SQLAlchemy.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION update_extra_class_payment_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = CURRENT_TIMESTAMP;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )

    op.execute(
        """
        DROP TRIGGER IF EXISTS trg_extra_class_payment_updated_at
        ON extra_class_payments;
        """
    )

    op.execute(
        """
        CREATE TRIGGER trg_extra_class_payment_updated_at
        BEFORE UPDATE ON extra_class_payments
        FOR EACH ROW
        EXECUTE FUNCTION update_extra_class_payment_updated_at();
        """
    )


def downgrade():
    op.execute(
        """
        DROP TRIGGER IF EXISTS trg_extra_class_payment_updated_at
        ON extra_class_payments;
        """
    )

    op.execute(
        """
        DROP FUNCTION IF EXISTS update_extra_class_payment_updated_at();
        """
    )

    op.alter_column(
        "extra_class_payments",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        existing_nullable=False,
        server_default=None,
    )

    op.alter_column(
        "extra_class_payments",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        existing_nullable=False,
        server_default=None,
    )
