"""add subject column to user.py

Revision ID: b1bf98c7cbc6
Revises: 75ca0410dc39
Create Date: 2026-07-19 15:55:37.949455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1bf98c7cbc6'
down_revision = '75ca0410dc39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
