"""Link questions to subjects

Revision ID: b87cc835186f
Revises: 7315c99b804a
Create Date: 2026-08-26 21:52:30.966158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b87cc835186f'
down_revision = '7315c99b804a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_question_subject_id'), ['subject_id'], unique=False)
        batch_op.create_foreign_key(None, 'subjects', ['subject_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_question_subject_id'))
        batch_op.drop_column('subject_id')

    # ### end Alembic commands ###
