"""add is_admin to user

Revision ID: ea5250f84682
Revises: 25ce3b4bcdac
Create Date: 2026-06-02 20:44:38.285775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea5250f84682'
down_revision = '25ce3b4bcdac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   with op.batch_alter_table('users', schema=None) as batch_op:
    batch_op.add_column(
        sa.Column(
            'is_admin',
            sa.Boolean(),
            nullable=False,
            server_default='false'
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
